name: Run Node.js Scraper

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-scraper:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run scraper
      run: node scraper.js

    - name: Check for changes
      run: |
        if (Test-Path "scrapedData.json") {
          Write-Output "scrapedData.json file exists."
          git status --short | Select-String "scrapedData.json" || Write-Output "No changes detected in scrapedData.json"
        } else {
          Write-Output "Error: scrapedData.json file does not exist!"
          exit 1
        }
      shell: pwsh

    - name: Commit and push scraped data
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add scrapedData.json
        git commit -m "Update scraped data" || Write-Output "No changes to commit."
        git push origin main
      shell: pwsh
